// Code generated by "stringer -type=BreakerType"; DO NOT EDIT.

package grpcbreaker

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BreakerGlobal-0]
	_ = x[BreakerService-1]
	_ = x[BreakerMethod-2]
	_ = x[BreakerCallSite-3]
}

const _BreakerType_name = "BreakerGlobalBreakerServiceBreakerMethodBreakerCallSite"

var _BreakerType_index = [...]uint8{0, 13, 27, 40, 55}

func (i BreakerType) String() string {
	if i < 0 || i >= BreakerType(len(_BreakerType_index)-1) {
		return "BreakerType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BreakerType_name[_BreakerType_index[i]:_BreakerType_index[i+1]]
}
