// Code generated by "stringer -type=State"; DO NOT EDIT.

package grpcbreaker

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Closed-1]
	_ = x[HalfOpen-2]
	_ = x[Open-3]
}

const _State_name = "UnknownClosedHalfOpenOpen"

var _State_index = [...]uint8{0, 7, 13, 21, 25}

func (i State) String() string {
	if i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
