// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pbtest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// SvcAClient is the client API for SvcA service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SvcAClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type svcAClient struct {
	cc grpc.ClientConnInterface
}

func NewSvcAClient(cc grpc.ClientConnInterface) SvcAClient {
	return &svcAClient{cc}
}

func (c *svcAClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/pbtest.SvcA/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SvcAServer is the server API for SvcA service.
// All implementations must embed UnimplementedSvcAServer
// for forward compatibility
type SvcAServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedSvcAServer()
}

// UnimplementedSvcAServer must be embedded to have forward compatible implementations.
type UnimplementedSvcAServer struct {
}

func (UnimplementedSvcAServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSvcAServer) mustEmbedUnimplementedSvcAServer() {}

// UnsafeSvcAServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SvcAServer will
// result in compilation errors.
type UnsafeSvcAServer interface {
	mustEmbedUnimplementedSvcAServer()
}

func RegisterSvcAServer(s grpc.ServiceRegistrar, srv SvcAServer) {
	s.RegisterService(&_SvcA_serviceDesc, srv)
}

func _SvcA_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SvcAServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbtest.SvcA/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SvcAServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SvcA_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbtest.SvcA",
	HandlerType: (*SvcAServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _SvcA_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "a.proto",
}
